### ISSUE TITLE
Use range_keys instead of range where value is not needed

### ISSUE THREAD

**Issue by webmaster128** [CosmWasm/cw-storage-plus#53]
We have a few cases where something like `.map(|(k, _)| k)` is done, i.e. drop the value as part of an iteration. CosmWasm 1.3 adds the ability to iterate over keys directly. In 1.4 this becomes very efficient. We should use it in this codebase whenever applicable.

**Comment by chipshort** [comment]
I found one internal usage in `Prefix::keys_raw` which is easy to change.
There is also one in `Prefix::keys`, but it converts them using `de_fn_kv` before mapping, which takes the full key-value-pair as argument, so I am not sure this can be changed in a non-breaking way.

**Comment by webmaster128** [comment]
> keys

Let's just schedule this for 2.0

**Comment by uint** [comment]
I started digging into the `Prefix::keys` part of this.

[This is made difficult by the way some storage items seem to require values to be deserialized so that they know how to deserialize the keys (???).](https://github.com/CosmWasm/cw-storage-plus/blob/main/src/indexes/multi.rs#L111-L118) I don't think I understand this whole machinery.

As a crutch, I could try to make providing a `de_fn_k` function to `Prefix` optional and see if things can work out like that. It feels like piling workarounds on top of a bad design though.

Have there been any discussions around rewriting `storage-plus` lately?
